# frontend react application
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: http://127.0.0.1:3000
    ports:
      - "80:80"
    restart: always
    networks:
      - todo-network
    depends_on:
      - backend

  # backend express application
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017
    ports:
      - "3000:3000"
    restart: always
    networks:
      - todo-network
    depends_on:
      - db
  # mongodb database
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always  
    networks:
      - todo-network
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data  

networks:
  todo-network:
volumes:
  mongo_data:
   
